"""
Orchestrates the enrichment of recommended games with short, Russian descriptions
generated by GPT based on the English summary from IGDB.
"""

import asyncio
import json

from sqlalchemy.orm import Session

from database.db import SessionLocal
from database.models import RecommendedGame
from pipeline.load.load_recommendations import (
    iter_games_missing_short_description,
    set_game_short_description,
)
from services.gpt_service import generate_short_description
from utils.logger import get_logger

# To avoid overwhelming the GPT service, limit concurrent requests.
CONCURRENT_GPT_REQUESTS = 3


async def _process_game(session: Session, game: RecommendedGame, semaphore: asyncio.Semaphore) -> bool:
    """
    Processes a single game: fetches GPT description and prepares session for commit.
    Returns True if a description was successfully added.
    """
    logger = get_logger("orchestrator.enrich_descriptions")

    async with semaphore:
        # 1. Extract English summary from the source_payload JSON.
        if not game.source_payload:
            return False

        try:
            payload = json.loads(game.source_payload)
            summary = payload.get("summary")
        except (json.JSONDecodeError, AttributeError):
            logger.warning(f"Could not parse source_payload for game: {game.title}")
            return False

        # Skip if summary is too short or non-existent to be useful.
        if not summary or not isinstance(summary, str) or len(summary.strip()) < 50:
            return False

        # 2. Call GPT service to generate a short description.
        logger.info(f"Generating description for: {game.title}")
        try:
            short_description = await generate_short_description(summary)
        except Exception as e:
            logger.error(f"GPT request failed for '{game.title}': {e}")
            return False

        # 3. Save the new description to the session.
        if short_description:
            if set_game_short_description(session, game, short_description):
                logger.info(f"Successfully generated and set description for: {game.title}")
                return True

    return False


def enrich_descriptions_with_gpt(process_limit: int = 10):
    """
    Finds recommended games without a short description, generates one using GPT,
    and saves it to the database.

    Args:
        process_limit: The maximum number of games to process in a single run.
    """
    logger = get_logger("orchestrator.enrich_descriptions")
    session = SessionLocal()
    updated_count = 0

    try:
        # 1. Get a batch of games that are missing a description.
        games_to_process = list(iter_games_missing_short_description(session, limit=process_limit))
        if not games_to_process:
            logger.info("No games found missing a short description.")
            return

        logger.info(f"Found {len(games_to_process)} games to process.")

        # 2. Create and run async tasks to process games concurrently.
        semaphore = asyncio.Semaphore(CONCURRENT_GPT_REQUESTS)

        async def main():
            tasks = [_process_game(session, game, semaphore) for game in games_to_process]
            results = await asyncio.gather(*tasks)
            return results

        results = asyncio.run(main())
        updated_count = sum(1 for r in results if r is True)

        # 3. Commit changes to the database if any were made.
        if updated_count > 0:
            session.commit()
            logger.info(f"Committed {updated_count} new short descriptions to the database.")
        else:
            logger.info("No descriptions were updated in this run.")
            session.rollback()

    except Exception:
        logger.exception("An error occurred during description enrichment.")
        session.rollback()
    finally:
        session.close()


if __name__ == "__main__":
    enrich_descriptions_with_gpt()
